sudo: required
dist: xenial
language: python

matrix:
    include:
        - python: 3.5
        - python: 3.6
        - python: 3.7
          dist: xenial
          sudo: true

before_install:
    - sudo apt-get update
    - sudo updatedb
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - if [ $TRAVIS_PYTHON_VERSION == "3.5" ]; then
        export CPLUS_INCLUDE_PATH=/opt/python/3.5.6/include/python3.5m;
      fi
    - if [ $TRAVIS_PYTHON_VERSION == "3.6" ]; then
        export CPLUS_INCLUDE_PATH=/opt/python/3.6.3/include/python3.6m;
      fi
    - if [ $TRAVIS_PYTHON_VERSION == "3.7" ]; then
        export CPLUS_INCLUDE_PATH=/opt/python/3.7.1/include/python3.7m;
      fi
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - hash -r
    - conda update --yes conda
    - conda info -a
    - sudo apt install -y libnfft3-dev

install:
    - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
    - source activate testenv
    - locate pyconfig.h
    - mkdir -p $HOME/.local/share/pysap
    - git clone https://github.com/CEA-COSMIC/pysap-data.git $HOME/.local/share/pysap/pysap-data
    - ln -s $HOME/.local/share/pysap/pysap-data/pysap-data/* $HOME/.local/share/pysap
    - ls -l $HOME/.local/share/pysap
    - pip install --upgrade pip
    - pip install matplotlib
    - pip install coverage nose pytest pytest-cov
    - pip install coveralls
    - pip install pycodestyle
    - pip install pybind11 nibabel pyqt5 pyqtgraph astropy 
    - pip install git+https://github.com/CEA-COSMIC/ModOpt.git
    - pip install git+https://github.com/AGrigis/pysphinxdoc.git
    - pip install sphinx==2.2.1
    - pushd ../
    - git clone https://github.com/CEA-COSMIC/pysap
    - cd pysap
    - python setup.py install
    - if [ $TRAVIS_PYTHON_VERSION == "3.5" ]; then
        export PATH=$PATH:$PWD/build/temp.linux-x86_64-3.5/extern/bin;
      fi
    - if [ $TRAVIS_PYTHON_VERSION == "3.6" ]; then
        export PATH=$PATH:$PWD/build/temp.linux-x86_64-3.6/extern/bin;
      fi
    - if [ $TRAVIS_PYTHON_VERSION == "3.7" ]; then
        export PATH=$PATH:$PWD/build/temp.linux-x86_64-3.7/extern/bin;
      fi
    - popd
    - export PYTHONPATH=$TRAVIS_BUILD_DIR/install:$PYTHONPATH
    - pip install -b $TRAVIS_BUILD_DIR/build -t $TRAVIS_BUILD_DIR/install --no-clean --upgrade .

script:
    - python setup.py test
    - pycodestyle mri --ignore="E121,E123,E126,E226,E24,E704,E402,E731,E722,E741,W503,W504,W605"
    - pycodestyle examples --ignore="E121,E123,E126,E226,E24,E704,E402,E731,E722,E741,W503,W504,W605"
    - cd doc/source
    - sphinx-build -T -E -W -d _build/doctrees-readthedocs -D language=en . _build/html

after_success:
    - coveralls
