# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "doc/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: 
          name: Install system packages
          command: |
            sudo -E apt-get -yq update
            sudo apt install -y cmake
            sudo apt install -y gcc
            sudo apt install -y libnfft3-dev
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --upgrade git+https://github.com/cea-cosmic/pysap
            pip install -r doc/requirements.txt
            pip list > doc/state.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "doc/state.txt" }}
      - run:
          name: Running CircleCI tests
          command: |
            . venv/bin/activate
            pip install --upgrade pip
            pip install Cython
            pip install -e .
            circleci tests glob examples/*.py | circleci tests split --split-by=timings > circleci_tests.txt
            cat circleci_test_files.txt
            python3 -m unittest $(cat circleci_tests.txt)
      - store_artifacts:
          path: test-reports
          destination: test-reports
