# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "doc/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: 
          name: Install system packages
          command: |
            sudo -E apt-get -yq update
            sudo apt install -y cmake
            sudo apt install -y gcc
            sudo apt install -y libnfft3-dev
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r doc/requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "doc/requirements.txt" }}
      - run:
          name: Running CircleCI tests
          command: |
            . venv/bin/activate
            pip install Cython
            pushd ../
            git clone https://github.com/CEA-COSMIC/pysap
            cd pysap
            python setup.py install
            if [ $TRAVIS_PYTHON_VERSION == "3.5" ]; then
              export PATH=$PATH:$PWD/build/temp.linux-x86_64-3.5/extern/bin;
            fi
            if [ $TRAVIS_PYTHON_VERSION == "3.6" ]; then
              export PATH=$PATH:$PWD/build/temp.linux-x86_64-3.6/extern/bin;
            fi
            if [ $TRAVIS_PYTHON_VERSION == "3.7" ]; then
              export PATH=$PATH:$PWD/build/temp.linux-x86_64-3.7/extern/bin;
            fi
            popd
            pip install -e .
            python .circleci/test_script.py
      - store_artifacts:
          path: test-reports
          destination: test-reports

